import schemathesis
import httpx
import pytest

BASE_URL = "https://petstore.swagger.io/v2"
SCHEMA_URL = "https://petstore.swagger.io/v2/swagger.json"

# Build a Schemathesis schema from the OpenAPI (Swagger) spec
schema = schemathesis.from_uri(SCHEMA_URL)

@pytest.mark.parametrize("case", schema.get_open_api_paths())
def test_schemathesis_property(case: schemathesis.models.Case) -> None:
    """
    Property-based tests generated by Schemathesis.
    Each generated case will be executed against the Petstore API
    and validated against the OpenAPI schema.
    """
    pass  # Placeholder to ensure pytest collects the decorator

# The canonical way to run Schemathesis with pytest is to use the @schema.parametrize()
# decorator on a test function. The following test leverages that approach to
# automatically generate and run many test cases derived from the OpenAPI spec.

@schema.parametrize()
def test_api(case: schemathesis.models.Case) -> None:
    """
    Property-based tests: Schemathesis will generate multiple test cases from the OpenAPI
    specification. Each case will perform an HTTP call and validate the response
    against the schema. We supply the base URL to ensure correct routing.
    """
    case.call_and_validate(base_url=BASE_URL)