import re
import requests
import pytest
import schemathesis

# Base URL and OpenAPI spec URL
BASE_URL = "https://petstore.swagger.io/v2"
OPENAPI_URL = "https://petstore.swagger.io/v2/swagger.json"

# Build a Schemathesis schema from the OpenAPI spec
schema = schemathesis.from_uri(OPENAPI_URL)

def _fill_path_params(path: str, path_params: dict) -> str:
    """
    Simple helper to substitute path parameters in a path like /pet/{petId}.
    """
    if not path_params:
        return path
    for key, value in (path_params or {}).items():
        path = path.replace("{" + key + "}", str(value))
    # If any placeholders remain, replace with a safe default
    path = re.sub(r"\{[^}]+\}", "1", path)
    return path

@schema.parametrize()
def test_schemathesis_property_test(case):
    """
    Property test generated by Schemathesis.

    This test constructs a request based on the case and validates the response
    against the OpenAPI schema. It also demonstrates path parameter filling and
    minimal request construction using requests.
    """
    # Build URL from base and path, substituting any path params if present
    path = case.path
    path_params = getattr(case, "path_parameters", {}) or {}
    path = _fill_path_params(path, path_params)
    url = f"{BASE_URL}{path}"

    # Build request components
    method = case.method
    headers = dict(case.headers or {})
    body = getattr(case, "body", None)
    if isinstance(body, (dict, list)):
        data = json.dumps(body)
        if "Content-Type" not in headers:
            headers["Content-Type"] = "application/json"
    else:
        data = None

    # Some cases may specify query parameters; attempt to pass if present
    params = getattr(case, "query", None)

    # Execute request
    response = requests.request(method=method, url=url, headers=headers, data=data, params=params, timeout=20)

    # Validate response against schema
    case.validate_response(response)