// Test file for: cal.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the Calculator class
const Calculator = require('../cal.js');

describe('Calculator', () => {
  // Test the Calculator class that was imported above

  describe('add method', () => {
    // Test the add method based on ACTUAL code analysis above
    test('should return the sum of two numbers', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = 5;
      const b = 3;

      // Act - call the method exactly as implemented
      const result = calculator.add(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe(8);
    });

    test('should return the sum of two negative numbers', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = -5;
      const b = -3;

      // Act - call the method exactly as implemented
      const result = calculator.add(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe(-8);
    });

    test('should return the sum of a positive and a negative number', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = 5;
      const b = -3;

      // Act - call the method exactly as implemented
      const result = calculator.add(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe(2);
    });
  });

  describe('subtract method', () => {
    // Test the subtract method based on ACTUAL code analysis above
    test('should return the difference of two numbers', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = 5;
      const b = 3;

      // Act - call the method exactly as implemented
      const result = calculator.subtract(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe(2);
    });

    test('should return the difference of two negative numbers', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = -5;
      const b = -3;

      // Act - call the method exactly as implemented
      const result = calculator.subtract(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe(-2);
    });

    test('should return the difference of a positive and a negative number', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = 5;
      const b = -3;

      // Act - call the method exactly as implemented
      const result = calculator.subtract(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe(8);
    });
  });

  describe('multiply method', () => {
    // Test the multiply method based on ACTUAL code analysis above
    test('should return the product of two numbers', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = 5;
      const b = 3;

      // Act - call the method exactly as implemented
      const result = calculator.multiply(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe(15);
    });

    test('should return the product of two negative numbers', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = -5;
      const b = -3;

      // Act - call the method exactly as implemented
      const result = calculator.multiply(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe(15);
    });

    test('should return the product of a positive and a negative number', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = 5;
      const b = -3;

      // Act - call the method exactly as implemented
      const result = calculator.multiply(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe(-15);
    });
  });

  describe('divide method', () => {
    // Test the divide method based on ACTUAL code analysis above
    test('should return the quotient of two numbers', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = 10;
      const b = 2;

      // Act - call the method exactly as implemented
      const result = calculator.divide(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe(5);
    });

    test('should return the quotient of two negative numbers', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = -10;
      const b = -2;

      // Act - call the method exactly as implemented
      const result = calculator.divide(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe(5);
    });

    test('should return the quotient of a positive and a negative number', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = 10;
      const b = -2;

      // Act - call the method exactly as implemented
      const result = calculator.divide(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe(-5);
    });

    test('should return an error message when dividing by zero', () => {
      // Arrange - set up initial state exactly as code expects
      const calculator = new Calculator();
      const a = 10;
      const b = 0;

      // Act - call the method exactly as implemented
      const result = calculator.divide(a, b);

      // Assert - verify the exact state changes that occur in the code
      expect(result).toBe('error: division by zero');
    });
  });
});
