// Test file for: cal.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the Calculator class
const Calculator = require('../cal.js');
// Import the standalone multiply function
const { multiply } = require('../cal.js');

describe('Calculator class', () => {
  describe('add method', () => {
    test('should add two numbers', () => {
      const calculator = new Calculator();
      const result = calculator.add(2, 3);
      expect(result).toBe(5);
    });

    test('should throw an error for non-numeric inputs', () => {
      const calculator = new Calculator();
      expect(() => calculator.add('a', 3)).toThrowError('Both arguments must be numbers');
    });

    test('should handle edge case of zero', () => {
      const calculator = new Calculator();
      const result = calculator.add(0, 5);
      expect(result).toBe(5);
    });

    test('should handle edge case of negative numbers', () => {
      const calculator = new Calculator();
      const result = calculator.add(-2, -3);
      expect(result).toBe(-5);
    });

    test('should handle edge case of large numbers', () => {
      const calculator = new Calculator();
      const result = calculator.add(1000000, 2000000);
      expect(result).toBe(3000000);
    });
  });

  describe('subtract method', () => {
    test('should subtract two numbers', () => {
      const calculator = new Calculator();
      const result = calculator.subtract(5, 2);
      expect(result).toBe(3);
    });

    test('should throw an error for non-numeric inputs', () => {
      const calculator = new Calculator();
      expect(() => calculator.subtract('a', 3)).toThrowError('Both arguments must be numbers');
    });

    test('should handle edge case of zero', () => {
      const calculator = new Calculator();
      const result = calculator.subtract(0, 5);
      expect(result).toBe(-5);
    });

    test('should handle edge case of negative numbers', () => {
      const calculator = new Calculator();
      const result = calculator.subtract(-2, -3);
      expect(result).toBe(1);
    });

    test('should handle edge case of large numbers', () => {
      const calculator = new Calculator();
      const result = calculator.subtract(2000000, 1000000);
      expect(result).toBe(1000000);
    });
  });

  describe('multiply method', () => {
    test('should multiply two numbers', () => {
      const calculator = new Calculator();
      const result = calculator.multiply(2, 3);
      expect(result).toBe(6);
    });

    test('should throw an error for non-numeric inputs', () => {
      const calculator = new Calculator();
      expect(() => calculator.multiply('a', 3)).toThrowError('Both arguments must be numbers');
    });

    test('should handle edge case of zero', () => {
      const calculator = new Calculator();
      const result = calculator.multiply(0, 5);
      expect(result).toBe(0);
    });

    test('should handle edge case of negative numbers', () => {
      const calculator = new Calculator();
      const result = calculator.multiply(-2, -3);
      expect(result).toBe(6);
    });

    test('should handle edge case of large numbers', () => {
      const calculator = new Calculator();
      const result = calculator.multiply(1000000, 2000000);
      expect(result).toBe(2000000000000);
    });
  });

  describe('divide method', () => {
    test('should divide two numbers', () => {
      const calculator = new Calculator();
      const result = calculator.divide(6, 2);
      expect(result).toBe(3);
    });

    test('should throw an error for non-numeric inputs', () => {
      const calculator = new Calculator();
      expect(() => calculator.divide('a', 3)).toThrowError('Both arguments must be numbers');
    });

    test('should throw an error for division by zero', () => {
      const calculator = new Calculator();
      expect(() => calculator.divide(6, 0)).toThrowError('Division by zero');
    });

    test('should handle edge case of zero', () => {
      const calculator = new Calculator();
      const result = calculator.divide(0, 5);
      expect(result).toBe(0);
    });

    test('should handle edge case of negative numbers', () => {
      const calculator = new Calculator();
      const result = calculator.divide(-6, -2);
      expect(result).toBe(3);
    });

    test('should handle edge case of large numbers', () => {
      const calculator = new Calculator();
      const result = calculator.divide(2000000, 1000000);
      expect(result).toBe(2);
    });
  });
});
