// Test file for: cal.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the Calculator class
const Calculator = require('../cal.js');

describe('Calculator', () => {
  describe('add', () => {
    test('should add two numbers', () => {
      const instance = new Calculator();
      const result = instance.add(5, 3);
      expect(result).toBe(8);
    });

    test('should throw error for non-numeric inputs', () => {
      const instance = new Calculator();
      expect(() => instance.add('a', 3)).toThrowError('Both arguments must be numbers');
    });

    test('should handle edge case: zero', () => {
      const instance = new Calculator();
      const result = instance.add(0, 5);
      expect(result).toBe(5);
    });

    test('should handle edge case: negative numbers', () => {
      const instance = new Calculator();
      const result = instance.add(-5, -3);
      expect(result).toBe(-8);
    });
  });

  describe('subtract', () => {
    test('should subtract two numbers', () => {
      const instance = new Calculator();
      const result = instance.subtract(5, 3);
      expect(result).toBe(2);
    });

    test('should throw error for non-numeric inputs', () => {
      const instance = new Calculator();
      expect(() => instance.subtract('a', 3)).toThrowError('Both arguments must be numbers');
    });

    test('should handle edge case: zero', () => {
      const instance = new Calculator();
      const result = instance.subtract(0, 5);
      expect(result).toBe(-5);
    });

    test('should handle edge case: negative numbers', () => {
      const instance = new Calculator();
      const result = instance.subtract(-5, -3);
      expect(result).toBe(-2);
    });
  });

  describe('multiply', () => {
    test('should multiply two numbers', () => {
      const instance = new Calculator();
      const result = instance.multiply(5, 3);
      expect(result).toBe(15);
    });

    test('should throw error for non-numeric inputs', () => {
      const instance = new Calculator();
      expect(() => instance.multiply('a', 3)).toThrowError('Both arguments must be numbers');
    });

    test('should handle edge case: zero', () => {
      const instance = new Calculator();
      const result = instance.multiply(0, 5);
      expect(result).toBe(0);
    });

    test('should handle edge case: negative numbers', () => {
      const instance = new Calculator();
      const result = instance.multiply(-5, -3);
      expect(result).toBe(15);
    });
  });

  describe('divide', () => {
    test('should divide two numbers', () => {
      const instance = new Calculator();
      const result = instance.divide(5, 3);
      expect(result).toBe(1.6666666666666667);
    });

    test('should throw error for non-numeric inputs', () => {
      const instance = new Calculator();
      expect(() => instance.divide('a', 3)).toThrowError('Both arguments must be numbers');
    });

    test('should throw error for division by zero', () => {
      const instance = new Calculator();
      expect(() => instance.divide(5, 0)).toThrowError('Division by zero');
    });

    test('should handle edge case: zero', () => {
      const instance = new Calculator();
      const result = instance.divide(0, 5);
      expect(result).toBe(0);
    });

    test('should handle edge case: negative numbers', () => {
      const instance = new Calculator();
      const result = instance.divide(-5, -3);
      expect(result).toBe(1.6666666666666667);
    });
  });

  describe('power', () => {
    test('should calculate power of two numbers', () => {
      const instance = new Calculator();
      const result = instance.power(5, 3);
      expect(result).toBe(125);
    });

    test('should throw error for non-numeric inputs', () => {
      const instance = new Calculator();
      expect(() => instance.power('a', 3)).toThrowError('Both arguments must be numbers');
    });

    test('should throw error for negative exponent', () => {
      const instance = new Calculator();
      expect(() => instance.power(5, -3)).toThrowError('Exponent must be non-negative');
    });

    test('should handle edge case: zero', () => {
      const instance = new Calculator();
      const result = instance.power(0, 5);
      expect(result).toBe(0);
    });

    test('should handle edge case: negative numbers', () => {
      const instance = new Calculator();
      const result = instance.power(-5, 3);
      expect(result).toBe(-125);
    });
  });

  describe('factorial', () => {
    test('should calculate factorial of a number', () => {
      const instance = new Calculator();
      const result = instance.factorial(5);
      expect(result).toBe(120);
    });

    test('should throw error for non-numeric inputs', () => {
      const instance = new Calculator();
      expect(() => instance.factorial('a')).toThrowError('Argument must be a number');
    });

    test('should throw error for negative numbers', () => {
      const instance = new Calculator();
      expect(() => instance.factorial(-5)).toThrowError(
        'Factorial is not defined for negative numbers'
      );
    });

    test('should handle edge case: zero', () => {
      const instance = new Calculator();
      const result = instance.factorial(0);
      expect(result).toBe(1);
    });

    test('should handle edge case: one', () => {
      const instance = new Calculator();
      const result = instance.factorial(1);
      expect(result).toBe(1);
    });
  });
});
