// Test file for: capitalize.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the capitalizeWords function
const capitalizeWords = require('../capitalize.js');

describe('capitalizeWords', () => {
  describe('function behavior', () => {
    test('should return capitalized string when input is a string', () => {
      const sentence = 'hello world';
      const result = capitalizeWords(sentence);
      expect(result).toBe('Hello World');
    });

    test('should throw error when input is not a string', () => {
      const nonStringInput = 123;
      expect(() => capitalizeWords(nonStringInput)).toThrowError('Input is not a string');
    });

    test('should handle empty string input', () => {
      const emptyString = '';
      const result = capitalizeWords(emptyString);
      expect(result).toBe('');
    });

    test('should handle single character string input', () => {
      const singleCharacter = 'a';
      const result = capitalizeWords(singleCharacter);
      expect(result).toBe('A');
    });

    test('should handle very long string input', () => {
      const longString = 'a'.repeat(100);
      const result = capitalizeWords(longString);
      expect(result).toBe(longString.charAt(0).toUpperCase() + longString.slice(1).toLowerCase());
    });

    test('should handle string with special characters', () => {
      const specialCharacters = 'hello@world!';
      const result = capitalizeWords(specialCharacters);
      expect(result).toBe(
        specialCharacters.charAt(0).toUpperCase() + specialCharacters.slice(1).toLowerCase()
      );
    });
  });

  describe('boundary value analysis', () => {
    test('should handle minimum length string input', () => {
      const minLength = 'a';
      const result = capitalizeWords(minLength);
      expect(result).toBe('A');
    });

    test('should handle maximum length string input', () => {
      const maxLength = 'a'.repeat(100);
      const result = capitalizeWords(maxLength);
      expect(result).toBe(maxLength.charAt(0).toUpperCase() + maxLength.slice(1).toLowerCase());
    });

    test('should handle zero length string input', () => {
      const zeroLength = '';
      const result = capitalizeWords(zeroLength);
      expect(result).toBe('');
    });

    test('should handle negative length string input', () => {
      const negativeLength = -1;
      expect(() => capitalizeWords(negativeLength)).toThrowError('Input is not a string');
    });
  });

  describe('equivalence class partitioning', () => {
    test('should handle valid string input', () => {
      const validString = 'hello world';
      const result = capitalizeWords(validString);
      expect(result).toBe('Hello World');
    });

    test('should handle invalid string input', () => {
      const invalidString = 123;
      expect(() => capitalizeWords(invalidString)).toThrowError('Input is not a string');
    });

    test('should handle boundary string input', () => {
      const boundaryString = 'a';
      const result = capitalizeWords(boundaryString);
      expect(result).toBe('A');
    });
  });

  describe('exact behavior verification', () => {
    test('should split input string into words', () => {
      const sentence = 'hello world';
      const words = capitalizeWords(sentence).split(' ');
      expect(words).toEqual(['Hello', 'World']);
    });

    test('should capitalize first letter of each word', () => {
      const sentence = 'hello world';
      const capitalizedWords = capitalizeWords(sentence).split(' ');
      expect(capitalizedWords.map((word) => word.charAt(0))).toEqual(['H', 'W']);
    });

    test('should lowercase remaining letters of each word', () => {
      const sentence = 'hello world';
      const capitalizedWords = capitalizeWords(sentence).split(' ');
      expect(capitalizedWords.map((word) => word.slice(1))).toEqual(['ello', 'orld']);
    });
  });

  describe('state change verification', () => {
    test('should not modify original input string', () => {
      const originalString = 'hello world';
      const capitalizedString = capitalizeWords(originalString);
      expect(originalString).toBe('hello world');
    });
  });

  describe('edge case verification', () => {
    test('should handle null input', () => {
      const nullInput = null;
      expect(() => capitalizeWords(nullInput)).toThrowError('Input is not a string');
    });

    test('should handle undefined input', () => {
      const undefinedInput = undefined;
      expect(() => capitalizeWords(undefinedInput)).toThrowError('Input is not a string');
    });
  });
});
