// Test file for: capitalize.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the capitalizeWords function
const capitalizeWords = require('../capitalize.js');

describe('capitalizeWords', () => {
  describe('input validation', () => {
    test('should throw an error for non-string input', () => {
      expect(() => capitalizeWords(123)).toThrowError('Input is not a string');
    });

    test('should throw an error for null input', () => {
      expect(() => capitalizeWords(null)).toThrowError('Input is not a string');
    });

    test('should throw an error for undefined input', () => {
      expect(() => capitalizeWords(undefined)).toThrowError('Input is not a string');
    });
  });

  describe('string input', () => {
    test('should capitalize the first letter of each word', () => {
      const sentence = 'hello world from javascript';
      const expected = 'Hello World From Javascript';
      expect(capitalizeWords(sentence)).toBe(expected);
    });

    test('should handle empty string input', () => {
      const sentence = '';
      const expected = '';
      expect(capitalizeWords(sentence)).toBe(expected);
    });

    test('should handle single-word input', () => {
      const sentence = 'hello';
      const expected = 'Hello';
      expect(capitalizeWords(sentence)).toBe(expected);
    });

    test('should handle multi-word input with punctuation', () => {
      const sentence = 'hello, world! from javascript.';
      const expected = 'Hello, World! From Javascript.';
      expect(capitalizeWords(sentence)).toBe(expected);
    });

    test('should handle very long string input', () => {
      const sentence =
        'hello world from javascript this is a very long string that should be capitalized correctly';
      const expected =
        'Hello World From Javascript This Is A Very Long String That Should Be Capitalized Correctly';
      expect(capitalizeWords(sentence)).toBe(expected);
    });
  });
});
