// Test file for: capitalize.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the capitalizeWords function
const capitalizeWords = require('../capitalize.js');

describe('capitalizeWords', () => {
  describe('input validation', () => {
    test('should throw an error for non-string input', () => {
      expect(() => capitalizeWords(123)).toThrowError('Input is not a string');
    });

    test('should throw an error for null input', () => {
      expect(() => capitalizeWords(null)).toThrowError('Input is not a string');
    });

    test('should throw an error for undefined input', () => {
      expect(() => capitalizeWords(undefined)).toThrowError('Input is not a string');
    });
  });

  describe('string input', () => {
    test('should capitalize the first letter of each word', () => {
      const result = capitalizeWords('hello world');
      expect(result).toBe('Hello World');
    });

    test('should handle empty strings', () => {
      const result = capitalizeWords('');
      expect(result).toBe('');
    });

    test('should handle single-word strings', () => {
      const result = capitalizeWords('hello');
      expect(result).toBe('Hello');
    });

    test('should handle strings with special characters', () => {
      const result = capitalizeWords('hello, world!');
      expect(result).toBe('Hello, World!');
    });

    test('should handle very long strings', () => {
      const longString = 'a'.repeat(100);
      const result = capitalizeWords(longString + ' ' + longString);
      expect(result).toBe(
        (longString + ' ' + longString)
          .split(' ')
          .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
          .join(' ')
      );
    });
  });

  describe('edge cases', () => {
    test('should handle strings with leading or trailing whitespace', () => {
      const result = capitalizeWords('   hello world   ');
      expect(result).toBe('Hello World');
    });

    test('should handle strings with multiple consecutive spaces', () => {
      const result = capitalizeWords('hello  world');
      expect(result).toBe('Hello World');
    });
  });
});
