// Test file for: divide.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the divide function
const divide = require('../divide.js');

describe('Divide Function', () => {
  describe('divide function', () => {
    test('should perform division with valid numbers', () => {
      const result = divide(10, 2);
      expect(result).toBe(5);
    });

    test('should throw error for non-numeric input', () => {
      expect(() => divide('a', 2)).toThrowError('a is not a number');
    });

    test('should throw error for division by zero', () => {
      expect(() => divide(10, 0)).toThrowError('Division by zero is not allowed');
    });

    test('should handle negative numbers', () => {
      const result = divide(-10, 2);
      expect(result).toBe(-5);
    });

    test('should handle large numbers', () => {
      const result = divide(1000000, 2);
      expect(result).toBe(500000);
    });

    test('should handle small numbers', () => {
      const result = divide(0.1, 2);
      expect(result).toBe(0.05);
    });

    test('should handle zero', () => {
      const result = divide(0, 2);
      expect(result).toBe(0);
    });
  });
});
