// Test file for: divide.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the divide function
const divide = require('../divide.js');

describe('divide function', () => {
  describe('numeric inputs', () => {
    test('should divide two positive numbers', () => {
      const result = divide(10, 2);
      expect(result).toBe(5);
    });

    test('should divide two negative numbers', () => {
      const result = divide(-10, -2);
      expect(result).toBe(5);
    });

    test('should divide a positive number by a negative number', () => {
      const result = divide(10, -2);
      expect(result).toBe(-5);
    });

    test('should divide a negative number by a positive number', () => {
      const result = divide(-10, 2);
      expect(result).toBe(-5);
    });

    test('should divide by zero', () => {
      expect(() => divide(10, 0)).toThrowError('Division by zero is not allowed');
    });

    test('should handle zero as input', () => {
      expect(() => divide(0, 2)).toThrowError('Division by zero is not allowed');
    });

    test('should handle zero as divisor', () => {
      expect(() => divide(10, 0)).toThrowError('Division by zero is not allowed');
    });

    test('should handle negative zero as input', () => {
      expect(() => divide(0, -2)).toThrowError('Division by zero is not allowed');
    });

    test('should handle negative zero as divisor', () => {
      expect(() => divide(-10, 0)).toThrowError('Division by zero is not allowed');
    });
  });

  describe('non-numeric inputs', () => {
    test('should throw an error for non-numeric input a', () => {
      expect(() => divide('a', 2)).toThrowError('a is not a number');
    });

    test('should throw an error for non-numeric input b', () => {
      expect(() => divide(10, 'b')).toThrowError('b is not a number');
    });

    test('should throw an error for non-numeric input a and b', () => {
      expect(() => divide('a', 'b')).toThrowError('a is not a number');
    });
  });
});
