// Test file for: duplicate.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the removeDuplicates function
const removeDuplicates = require('../duplicate.js');

describe('removeDuplicates', () => {
  describe('array input', () => {
    test('should remove duplicates from an array', () => {
      const input = [1, 2, 2, 3, 4, 4, 5];
      const result = removeDuplicates(input);
      expect(result).toEqual([1, 2, 3, 4, 5]);
    });

    test('should throw an error for non-array input', () => {
      const input = 'not an array';
      expect(() => removeDuplicates(input)).toThrowError('Input is not an array');
    });

    test('should handle empty array', () => {
      const input = [];
      const result = removeDuplicates(input);
      expect(result).toEqual([]);
    });

    test('should handle array with single element', () => {
      const input = [1];
      const result = removeDuplicates(input);
      expect(result).toEqual([1]);
    });

    test('should handle large array', () => {
      const input = [1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8, 9];
      const result = removeDuplicates(input);
      expect(result).toEqual([1, 2, 3, 4, 5, 6, 7, 8, 9]);
    });
  });

  describe('edge cases', () => {
    test('should handle null input', () => {
      const input = null;
      expect(() => removeDuplicates(input)).toThrowError('Input is not an array');
    });

    test('should handle undefined input', () => {
      const input = undefined;
      expect(() => removeDuplicates(input)).toThrowError('Input is not an array');
    });

    test('should handle non-array object input', () => {
      const input = { a: 1, b: 2 };
      expect(() => removeDuplicates(input)).toThrowError('Input is not an array');
    });
  });
});
