// Test file for: duplicate.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the removeDuplicates function
const removeDuplicates = require('../duplicate.js');

describe('removeDuplicates', () => {
  describe('array input', () => {
    test('should return an array with unique elements', () => {
      const input = [1, 2, 2, 3, 4, 4, 5];
      const result = removeDuplicates(input);
      expect(result).toEqual([1, 2, 3, 4, 5]);
    });

    test('should return an empty array for an empty input array', () => {
      const input = [];
      const result = removeDuplicates(input);
      expect(result).toEqual([]);
    });

    test('should return an array with a single element for a single-element input array', () => {
      const input = [1];
      const result = removeDuplicates(input);
      expect(result).toEqual([1]);
    });

    test('should return an array with unique elements for a large input array', () => {
      const input = [1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8, 9];
      const result = removeDuplicates(input);
      expect(result).toEqual([1, 2, 3, 4, 5, 6, 7, 8, 9]);
    });
  });

  describe('non-array input', () => {
    test('should throw an error for a non-array input', () => {
      const input = 'hello';
      expect(() => removeDuplicates(input)).toThrowError('Input is not an array');
    });

    test('should throw an error for a null input', () => {
      const input = null;
      expect(() => removeDuplicates(input)).toThrowError('Input is not an array');
    });

    test('should throw an error for an undefined input', () => {
      const input = undefined;
      expect(() => removeDuplicates(input)).toThrowError('Input is not an array');
    });

    test('should throw an error for a boolean input', () => {
      const input = true;
      expect(() => removeDuplicates(input)).toThrowError('Input is not an array');
    });

    test('should throw an error for a number input', () => {
      const input = 123;
      expect(() => removeDuplicates(input)).toThrowError('Input is not an array');
    });

    test('should throw an error for a string input', () => {
      const input = 'hello';
      expect(() => removeDuplicates(input)).toThrowError('Input is not an array');
    });
  });
});
