// Test file for: mathUtils.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the factorial function
const { factorial } = require('../mathUtils.js');

describe('Factorial Function', () => {
  describe('Positive Input', () => {
    test('should return the factorial of a positive number', () => {
      const result = factorial(5);
      expect(result).toBe(120);
    });

    test('should return 1 for input 0 or 1', () => {
      const result = factorial(0);
      expect(result).toBe(1);
      const result2 = factorial(1);
      expect(result2).toBe(1);
    });
  });

  describe('Negative Input', () => {
    test('should return -1 for negative input', () => {
      const result = factorial(-5);
      expect(result).toBe(-1);
    });
  });

  describe('Edge Cases', () => {
    test('should return -1 for non-numeric input', () => {
      expect(() => factorial('a')).toThrowError('Factorial is not defined for non-numeric input');
    });

    test('should return -1 for non-integer input', () => {
      expect(() => factorial(3.5)).toThrowError('Factorial is not defined for non-integer input');
    });
  });

  describe('Boundary Value Analysis', () => {
    test('should return 1 for input 0', () => {
      const result = factorial(0);
      expect(result).toBe(1);
    });

    test('should return 1 for input 1', () => {
      const result = factorial(1);
      expect(result).toBe(1);
    });

    test('should return a large factorial value for a large input', () => {
      const result = factorial(20);
      expect(result).toBeGreaterThan(2.43e18);
    });
  });

  describe('Equivalence Class Partitioning', () => {
    test('should return the same result for equivalent inputs', () => {
      const result1 = factorial(5);
      const result2 = factorial(5);
      expect(result1).toBe(result2);
    });

    test('should return different results for different inputs', () => {
      const result1 = factorial(5);
      const result2 = factorial(6);
      expect(result1).not.toBe(result2);
    });
  });
});
