// Test file for: mathUtils.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the factorial function
const { factorial } = require('../mathUtils.js');

describe('Factorial Function', () => {
  describe('Basic Functionality', () => {
    test('should calculate factorial correctly for positive numbers', () => {
      const result = factorial(5);
      expect(result).toBe(120);
    });

    test('should return 1 for 0 and 1', () => {
      expect(factorial(0)).toBe(1);
      expect(factorial(1)).toBe(1);
    });
  });

  describe('Edge Cases', () => {
    test('should return -1 for negative numbers', () => {
      const result = factorial(-1);
      expect(result).toBe(-1);
    });
  });
});
