// Test file for: mathUtils.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the factorial function
const { factorial } = require('../mathUtils.js');

describe('Factorial Function', () => {
  describe('Positive Input', () => {
    test('should return the factorial of a positive number', () => {
      const result = factorial(5);
      expect(result).toBe(120);
    });

    test('should return the factorial of a larger positive number', () => {
      const result = factorial(10);
      expect(result).toBe(3628800);
    });
  });

  describe('Zero Input', () => {
    test('should return 1 for input 0', () => {
      const result = factorial(0);
      expect(result).toBe(1);
    });
  });

  describe('Negative Input', () => {
    test('should return -1 for negative input', () => {
      const result = factorial(-5);
      expect(result).toBe(-1);
    });
  });

  describe('Edge Cases', () => {
    test('should return 1 for input 1', () => {
      const result = factorial(1);
      expect(result).toBe(1);
    });

    test('should return -1 for input less than 0', () => {
      const result = factorial(-10);
      expect(result).toBe(-1);
    });

    test('should return -1 for input not an integer', () => {
      const result = factorial(3.5);
      expect(result).toBe(-1);
    });

    test('should return -1 for input not a number', () => {
      const result = factorial('hello');
      expect(result).toBe(-1);
    });
  });
});
