// Test file for: multiply.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the multiply function
const multiply = require('../multiply.js');

describe('Multiply Function', () => {
  describe('Basic Multiplication', () => {
    test('should multiply two positive numbers', () => {
      const result = multiply(5, 1);
      expect(result).toBe(5);
    });

    test('should multiply two negative numbers', () => {
      const result = multiply(-5, -1);
      expect(result).toBe(5);
    });

    test('should multiply a positive and a negative number', () => {
      const result = multiply(5, -1);
      expect(result).toBe(-5);
    });

    test('should multiply zero with any number', () => {
      const result = multiply(0, 5);
      expect(result).toBe(0);
    });
  });

  describe('Boundary Value Analysis', () => {
    test('should handle minimum integer value', () => {
      const result = multiply(-2147483648, 1);
      expect(result).toBe(-2147483648);
    });

    test('should handle maximum integer value', () => {
      const result = multiply(2147483647, 1);
      expect(result).toBe(2147483647);
    });

    test('should handle zero', () => {
      const result = multiply(0, 0);
      expect(result).toBe(0);
    });

    test('should handle negative zero', () => {
      const result = multiply(-0, 0);
      expect(result).toBe(0);
    });

    test('should handle NaN', () => {
      const result = multiply(NaN, 0);
      expect(result).toBe(NaN);
    });
  });

  describe('Equivalence Class Partitioning', () => {
    test('should handle valid positive numbers', () => {
      const result = multiply(5, 1);
      expect(result).toBe(5);
    });

    test('should handle valid negative numbers', () => {
      const result = multiply(-5, -1);
      expect(result).toBe(5);
    });

    test('should handle valid zero', () => {
      const result = multiply(0, 0);
      expect(result).toBe(0);
    });

    test('should handle invalid inputs (NaN)', () => {
      const result = multiply(NaN, 0);
      expect(result).toBe(NaN);
    });
  });

  describe('Exact Behavior Verification', () => {
    test('should return zero when either input is zero', () => {
      const result = multiply(0, 5);
      expect(result).toBe(0);
    });

    test('should return zero when both inputs are zero', () => {
      const result = multiply(0, 0);
      expect(result).toBe(0);
    });

    test('should return NaN when either input is NaN', () => {
      const result = multiply(NaN, 5);
      expect(result).toBe(NaN);
    });
  });

  describe('Edge Case Verification', () => {
    test('should handle null input', () => {
      expect(() => multiply(null, 5)).toThrowError('Cannot multiply null by a number');
    });

    test('should handle undefined input', () => {
      expect(() => multiply(undefined, 5)).toThrowError('Cannot multiply undefined by a number');
    });

    test('should handle non-numeric input', () => {
      expect(() => multiply('a', 5)).toThrowError('Cannot multiply non-numeric value by a number');
    });
  });
});
