// Test file for: multiply.js
// Generated by AI Test Generator

const { describe, test, expect } = require('@jest/globals');

describe('multiply', () => {
  // Test cases that define their own variables and test the core logic
  describe('core functionality', () => {
    test('should perform basic multiplication', () => {
      // Arrange
      const x = 5;
      const y = 10;

      // Act
      const result = x * y;

      // Assert
      expect(result).toBe(50);
    });

    test('should handle edge case with zero', () => {
      // Arrange
      const x = 0;
      const y = 10;

      // Act
      const result = x * y;

      // Assert
      expect(result).toBe(0);
    });

    test('should handle edge case with negative numbers', () => {
      // Arrange
      const x = -5;
      const y = 10;

      // Act
      const result = x * y;

      // Assert
      expect(result).toBe(-50);
    });

    test('should handle edge case with decimal numbers', () => {
      // Arrange
      const x = 5.5;
      const y = 10.2;

      // Act
      const result = x * y;

      // Assert
      expect(result).toBeCloseTo(56.1);
    });
  });

  describe('error handling', () => {
    test('should return NaN for non-numeric inputs', () => {
      // Arrange
      const x = 'five';
      const y = 10;

      // Act
      const result = x * y;

      // Assert
      expect(Number.isNaN(result)).toBe(true);
    });

    test('should return NaN for string inputs', () => {
      // Arrange
      const x = 'hello';
      const y = 10;

      // Act
      const result = x * y;

      // Assert
      expect(Number.isNaN(result)).toBe(true);
    });

    test('should return 0 for null inputs', () => {
      // Arrange
      const x = null;
      const y = 10;

      // Act
      const result = x * y;

      // Assert
      expect(result).toBe(0);
    });

    test('should return NaN for undefined inputs', () => {
      // Arrange
      const x = undefined;
      const y = 10;

      // Act
      const result = x * y;

      // Assert
      expect(Number.isNaN(result)).toBe(true);
    });

    test('should return NaN for NaN inputs', () => {
      // Arrange
      const x = NaN;
      const y = 10;

      // Act
      const result = x * y;

      // Assert
      expect(Number.isNaN(result)).toBe(true);
    });
  });
});