// Test file for: string-utils.js
// Generated by AI Test Generator
// Tests verify EXACT code behavior, no assumptions

const { describe, test, expect } = require('@jest/globals');
// Import the string utility functions
const { capitalize, reverseString, isPalindrome } = require('../string-utils.js');

describe('String Utility Functions', () => {
  describe('capitalize', () => {
    test('should return an empty string for non-string inputs', () => {
      expect(capitalize(null)).toBe('');
      expect(capitalize(undefined)).toBe('');
      expect(capitalize(123)).toBe('');
      expect(capitalize(true)).toBe('');
      expect(capitalize(false)).toBe('');
    });

    test('should capitalize the first letter of a string', () => {
      expect(capitalize('hello')).toBe('Hello');
      expect(capitalize('world')).toBe('World');
      expect(capitalize('javascript')).toBe('Javascript');
    });

    test('should leave non-string inputs unchanged', () => {
      expect(capitalize('hello')).toBe('Hello');
      expect(capitalize(123)).toBe('');
      expect(capitalize(true)).toBe('');
      expect(capitalize(false)).toBe('');
    });
  });

  describe('reverseString', () => {
    test('should return an empty string for non-string inputs', () => {
      expect(reverseString(null)).toBe('');
      expect(reverseString(undefined)).toBe('');
      expect(reverseString(123)).toBe('');
      expect(reverseString(true)).toBe('');
      expect(reverseString(false)).toBe('');
    });

    test('should reverse the characters in a string', () => {
      expect(reverseString('hello')).toBe('olleh');
      expect(reverseString('world')).toBe('dlrow');
      expect(reverseString('javascript')).toBe('tpircsaj');
    });

    test('should leave non-string inputs unchanged', () => {
      expect(reverseString('hello')).toBe('olleh');
      expect(reverseString(123)).toBe('');
      expect(reverseString(true)).toBe('');
      expect(reverseString(false)).toBe('');
    });
  });

  describe('isPalindrome', () => {
    test('should return false for non-string inputs', () => {
      expect(isPalindrome(null)).toBe(false);
      expect(isPalindrome(undefined)).toBe(false);
      expect(isPalindrome(123)).toBe(false);
      expect(isPalindrome(true)).toBe(false);
      expect(isPalindrome(false)).toBe(false);
    });

    test('should return true for palindromic strings', () => {
      expect(isPalindrome('madam')).toBe(true);
      expect(isPalindrome('radar')).toBe(true);
      expect(isPalindrome('level')).toBe(true);
    });

    test('should return false for non-palindromic strings', () => {
      expect(isPalindrome('hello')).toBe(false);
      expect(isPalindrome('world')).toBe(false);
      expect(isPalindrome('javascript')).toBe(false);
    });

    test('should ignore non-alphanumeric characters and case', () => {
      expect(isPalindrome('A man, a plan, a canal: Panama')).toBe(true);
      expect(isPalindrome('Was it a car or a cat I saw?')).toBe(true);
    });
  });
});
